alert("Dark concrete pillars pierce the night sky. You're walking down a lazy river dividing the looming city in half. It feels cold so you take a seat on a bench and put your arms inside your coat. It's been many years since moved out, missing the voice of your mother and the warmth of her home.")
const doing = prompt('A dark figure approaches you from the side and sits beside you. They\'re tapping a cane on the ground rhythmically. "What are you doing here?"')
alert('They reach out with fingers twisted with age, and point at you. "You used to be different" they uttered in a low, raspy voice "Your light has grown dim"')
alert("This is not news to you. As the years passed, the last of your happy memories have been fading away.")
const want = prompt('Slowly drops of rain start to tap the ground. "What do you really want?" the man asks.')
alert('"You say you want ' + want + '" yet you are still sitting here, ' + doing + ' in the freezing rain.')